eng2dan = {
'Qatar':"Qatar", 
'Portugal':"Portugal",
'Switzerland':"Schweiz", 
'Belgium':"Belgien", 
'Spain':"Spanien", 
'Germany':"Tyskland",
'Morocco':"Marokko", 
'Mexico':"Mexico", 
'France':"Frankrig", 
'Argentina':"Argentina", 
'USA':"USA", 
'Senegal':"Senegal",
'England':"England", 
'Denmark':"Danmark", 
'Brazil':"Brasilien", 
'Japan':"Japan", 
'Wales':"Wales", 
'Poland':"Polen",
'Tunisia':"Tunesien", 
'Croatia':"Kroatien", 
'Netherlands':"Holland", 
'Cameroon':"Cameroun", 
'Costa Rica':"Costa Rica",
'Canada':"Canada", 
'Saudi Arabia':"Saudi-Arabien", 
'Australia':"Australien", 
'Iran':"Iran", 
'Ecuador':"Ecuador", 
'Ghana':"Ghana",
'Serbia':"Serbien",
"Uruguay":"Uruguay",
'South_Korea':"Sydkorea"
}
